[project]
name = "pyex-flask-profile-login-edit"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "Flask==3.1.2",
    "Flask-SQLAlchemy==3.1.1",
    "psycopg2-binary==2.9.11",
    "pytest==8.3.4",
    "pytest-flask==1.3.0"
]
